#!/usr/bin/env python3
"""Generate the Metro Cyprus weekly merchant and venue PDF report.

The report is intentionally data-source agnostic. It accepts CSV exports in a
long metrics format so the same renderer can be fed from Snowflake, Looker, or
manual exports without changing the PDF layout.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.figure import Figure

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from reports.metro_cyprus_data import (  # noqa: E402
    ADDITION_DEDUCTION_METRICS,
    MERCHANT_NAME,
    MetricRecord,
    MONTHLY_PICKER_COLUMNS,
    OPERATIONS_METRICS,
    PICKER_METRICS,
    PURCHASE_METRICS,
    QUALITY_METRICS,
    WOLT_PLUS_METRICS,
    aggregate_metric,
    format_value,
    known_venues,
    load_monthly_picker,
    load_weekly_metrics,
    output_path_for,
    parse_date,
    previous_full_week,
    records_for_metric,
    records_for_venue,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--weekly-metrics",
        type=Path,
        default=Path("data/weekly_metrics.csv"),
        help="CSV with weekly metrics in long format.",
    )
    parser.add_argument(
        "--monthly-picker",
        type=Path,
        default=Path("data/monthly_picker_metrics.csv"),
        help="CSV with monthly picker detail rows.",
    )
    parser.add_argument(
        "--period-start",
        type=str,
        default=None,
        help="Report period start date, YYYY-MM-DD. Defaults to previous Monday.",
    )
    parser.add_argument(
        "--period-end",
        type=str,
        default=None,
        help="Report period end date, YYYY-MM-DD. Defaults to previous Sunday.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output PDF path. Defaults to reports/output/metro_cyprus_weekly_report_<period>.pdf.",
    )
    return parser.parse_args()


def apply_theme(fig: Figure) -> None:
    fig.patch.set_facecolor("#F7F9FB")


def add_header(fig: Figure, title: str, subtitle: str) -> None:
    fig.text(0.05, 0.955, title, fontsize=20, fontweight="bold", color="#102A43")
    fig.text(0.05, 0.925, subtitle, fontsize=10, color="#52606D")
    fig.text(0.95, 0.955, "Wolt x Metro Cyprus", ha="right", fontsize=10, color="#00AEEF")


def add_footer(fig: Figure, data_note: str) -> None:
    fig.text(0.05, 0.035, data_note, fontsize=8, color="#829AB1")
    fig.text(0.95, 0.035, "Generated by reports/generate_metro_cyprus_weekly_report.py", ha="right", fontsize=8, color="#829AB1")


def add_kpi_card(fig: Figure, x: float, y: float, w: float, h: float, title: str, value: str, accent: str) -> None:
    ax = fig.add_axes([x, y, w, h])
    ax.set_facecolor("white")
    for spine in ax.spines.values():
        spine.set_color("#D9E2EC")
    ax.set_xticks([])
    ax.set_yticks([])
    ax.axhline(0.96, color=accent, linewidth=5)
    ax.text(0.05, 0.70, title, transform=ax.transAxes, fontsize=9, color="#52606D", va="center")
    ax.text(0.05, 0.33, value, transform=ax.transAxes, fontsize=18, fontweight="bold", color="#102A43", va="center")


def add_placeholder(ax, title: str, message: str = "No source data available for this metric.") -> None:
    ax.set_facecolor("white")
    ax.set_title(title, loc="left", fontsize=11, fontweight="bold", color="#102A43")
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_color("#D9E2EC")
    ax.text(
        0.5,
        0.5,
        message,
        ha="center",
        va="center",
        transform=ax.transAxes,
        fontsize=10,
        color="#829AB1",
        wrap=True,
    )


def plot_bar(ax, records: list[MetricRecord], title: str, max_bars: int = 12) -> None:
    ax.set_facecolor("white")
    ax.set_title(title, loc="left", fontsize=11, fontweight="bold", color="#102A43")
    if not records:
        add_placeholder(ax, title)
        return

    grouped: dict[str, float] = defaultdict(float)
    for record in records:
        label = record.dimension_value or record.venue_name or record.metric
        grouped[label] += record.value
    items = sorted(grouped.items(), key=lambda item: item[1], reverse=True)[:max_bars]
    labels = [item[0] for item in items]
    values = [item[1] for item in items]
    ax.barh(labels[::-1], values[::-1], color="#00AEEF")
    ax.grid(axis="x", color="#D9E2EC", linewidth=0.8)
    ax.tick_params(axis="both", labelsize=8, colors="#334E68")
    for spine in ax.spines.values():
        spine.set_visible(False)


def plot_line(ax, records: list[MetricRecord], title: str) -> None:
    ax.set_facecolor("white")
    ax.set_title(title, loc="left", fontsize=11, fontweight="bold", color="#102A43")
    if not records:
        add_placeholder(ax, title)
        return

    grouped: dict[str, float] = defaultdict(float)
    for record in records:
        label = record.dimension_value or record.period_start or record.metric
        grouped[label] += record.value
    items = sorted(grouped.items(), key=lambda item: item[0])
    labels = [item[0] for item in items]
    values = [item[1] for item in items]
    ax.plot(labels, values, color="#00AEEF", marker="o", linewidth=2)
    ax.fill_between(labels, values, color="#B3ECFF", alpha=0.35)
    ax.grid(axis="y", color="#D9E2EC", linewidth=0.8)
    ax.tick_params(axis="x", labelrotation=45, labelsize=7, colors="#334E68")
    ax.tick_params(axis="y", labelsize=8, colors="#334E68")
    for spine in ax.spines.values():
        spine.set_visible(False)


def plot_metric_table(ax, records: list[MetricRecord], metrics: list[str], title: str) -> None:
    ax.set_facecolor("white")
    ax.set_title(title, loc="left", fontsize=11, fontweight="bold", color="#102A43")
    ax.axis("off")
    rows = []
    for metric in metrics:
        value, unit = aggregate_metric(records, metric)
        rows.append([metric, format_value(value, unit)])
    table = ax.table(cellText=rows, colLabels=["Metric", "Value"], loc="center", cellLoc="left", colLoc="left")
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1, 1.45)
    for (row, col), cell in table.get_celld().items():
        cell.set_edgecolor("#D9E2EC")
        if row == 0:
            cell.set_text_props(weight="bold", color="#102A43")
            cell.set_facecolor("#E6F7FF")
        else:
            cell.set_facecolor("white")


def plot_monthly_picker_table(ax, rows: list[dict[str, str]]) -> None:
    ax.set_facecolor("white")
    ax.set_title("Monthly Picker Metrics", loc="left", fontsize=11, fontweight="bold", color="#102A43")
    ax.axis("off")
    if not rows:
        add_placeholder(
            ax,
            "Monthly Picker Metrics",
            "No monthly picker detail export was provided.",
        )
        return
    visible_rows = [[row[column] for column in MONTHLY_PICKER_COLUMNS] for row in rows[:18]]
    table = ax.table(cellText=visible_rows, colLabels=MONTHLY_PICKER_COLUMNS, loc="center", cellLoc="left", colLoc="left")
    table.auto_set_font_size(False)
    table.set_fontsize(6)
    table.scale(1, 1.25)
    for (row_idx, _), cell in table.get_celld().items():
        cell.set_edgecolor("#D9E2EC")
        if row_idx == 0:
            cell.set_text_props(weight="bold", color="#102A43")
            cell.set_facecolor("#E6F7FF")
        else:
            cell.set_facecolor("white")


def build_merchant_preview(
    pdf: PdfPages,
    records: list[MetricRecord],
    start: date,
    end: date,
    data_note: str,
) -> None:
    fig = plt.figure(figsize=(11.69, 8.27))
    apply_theme(fig)
    add_header(fig, f"{MERCHANT_NAME} Weekly Report", f"Merchant preview | {start:%d %b %Y} - {end:%d %b %Y}")

    kpis = [
        ("Group Orders", "Group orders", "#00AEEF"),
        ("Group Gross Value", "Venue Group Gross Value", "#2F80ED"),
        ("W+ Orders", "W+ Orders", "#10B981"),
        ("Ops Performance", "Ops Performance", "#F59E0B"),
        ("POFR Group", "POFR Group %", "#8B5CF6"),
        ("Lost Sales GOV", "Lost sales GOV EUR", "#EF4444"),
    ]
    positions = [
        (0.05, 0.73),
        (0.365, 0.73),
        (0.68, 0.73),
        (0.05, 0.57),
        (0.365, 0.57),
        (0.68, 0.57),
    ]
    for (title, metric, color), (x, y) in zip(kpis, positions):
        value, unit = aggregate_metric(records, metric)
        add_kpi_card(fig, x, y, 0.27, 0.12, title, format_value(value, unit), color)

    ax_orders = fig.add_axes([0.05, 0.26, 0.42, 0.22])
    plot_bar(ax_orders, records_for_metric(records, "Orders per venue"), "Orders per Venue")
    ax_gov = fig.add_axes([0.53, 0.26, 0.42, 0.22])
    plot_bar(ax_gov, records_for_metric(records, "Gross Value per Venue"), "Gross Value per Venue")
    ax_hour = fig.add_axes([0.05, 0.08, 0.42, 0.13])
    plot_line(ax_hour, records_for_metric(records, "Orders per Hour"), "Orders per Hour")
    ax_ops = fig.add_axes([0.53, 0.08, 0.42, 0.13])
    plot_metric_table(ax_ops, records, ["POFR Group %", "Substitution %", "% Unfulfilled Items", "% Late Orders"], "Operations Snapshot")

    add_footer(fig, data_note)
    pdf.savefig(fig)
    plt.close(fig)


def build_metric_section(
    pdf: PdfPages,
    title: str,
    subtitle: str,
    records: list[MetricRecord],
    metrics: list[str],
    chart_metrics: list[str],
    start: date,
    end: date,
    data_note: str,
) -> None:
    fig = plt.figure(figsize=(11.69, 8.27))
    apply_theme(fig)
    add_header(fig, title, f"{subtitle} | {start:%d %b %Y} - {end:%d %b %Y}")

    table_ax = fig.add_axes([0.05, 0.12, 0.38, 0.72])
    plot_metric_table(table_ax, records, metrics, "Metric Values")

    chart_slots = [
        [0.49, 0.56, 0.43, 0.28],
        [0.49, 0.12, 0.43, 0.32],
    ]
    for slot, metric in zip(chart_slots, chart_metrics):
        ax = fig.add_axes(slot)
        metric_records = records_for_metric(records, metric)
        if "Hour" in metric or "Day" in metric:
            plot_line(ax, metric_records, metric)
        else:
            plot_bar(ax, metric_records, metric)

    add_footer(fig, data_note)
    pdf.savefig(fig)
    plt.close(fig)


def build_venue_page(
    pdf: PdfPages,
    venue_name: str,
    records: list[MetricRecord],
    start: date,
    end: date,
    data_note: str,
) -> None:
    venue_records = records_for_venue(records, venue_name)
    fig = plt.figure(figsize=(11.69, 8.27))
    apply_theme(fig)
    add_header(fig, f"{venue_name}", f"Venue performance | {start:%d %b %Y} - {end:%d %b %Y}")

    kpis = [
        ("Orders", "Orders per venue", "#00AEEF"),
        ("Gross Value", "Gross Value per Venue", "#2F80ED"),
        ("Avg Basket", "Average Basket Value per Venue", "#10B981"),
        ("POFR", "POFR %", "#8B5CF6"),
        ("Rating", "Rating per Store", "#F59E0B"),
        ("Late Orders", "% Late Orders", "#EF4444"),
    ]
    positions = [
        (0.05, 0.73),
        (0.365, 0.73),
        (0.68, 0.73),
        (0.05, 0.57),
        (0.365, 0.57),
        (0.68, 0.57),
    ]
    for (title, metric, color), (x, y) in zip(kpis, positions):
        value, unit = aggregate_metric(venue_records, metric)
        add_kpi_card(fig, x, y, 0.27, 0.12, title, format_value(value, unit), color)

    ax_day = fig.add_axes([0.05, 0.31, 0.42, 0.18])
    plot_line(ax_day, records_for_metric(venue_records, "Order per Day per Store"), "Orders per Day")
    ax_ops = fig.add_axes([0.53, 0.31, 0.42, 0.18])
    plot_metric_table(
        ax_ops,
        venue_records,
        ["Substitution %", "% Unfulfilled Items", "Punctuality per Venue", "Average Delivery Time per Venue", "Prep Time per Venue"],
        "Operations",
    )
    ax_quality = fig.add_axes([0.05, 0.08, 0.42, 0.17])
    plot_metric_table(
        ax_quality,
        venue_records,
        ["Rejections % per Venue", "Offline % per Venue (New)", "Offline Hours per Venue (New)", "Lost sales %GOV"],
        "Quality",
    )
    ax_picker = fig.add_axes([0.53, 0.08, 0.42, 0.17])
    plot_bar(ax_picker, records_for_metric(venue_records, "Picker Usage per Store"), "Picker Usage")

    add_footer(fig, data_note)
    pdf.savefig(fig)
    plt.close(fig)


def build_no_venue_page(pdf: PdfPages, start: date, end: date, data_note: str) -> None:
    fig = plt.figure(figsize=(11.69, 8.27))
    apply_theme(fig)
    add_header(fig, "Per-Venue Report Pages", f"{start:%d %b %Y} - {end:%d %b %Y}")
    ax = fig.add_axes([0.12, 0.2, 0.76, 0.5])
    add_placeholder(
        ax,
        "Venue-level data required",
        "No venue-level weekly metrics were available. Once data/weekly_metrics.csv contains venue_name values, this section will render one page per Metro Cyprus venue.",
    )
    add_footer(fig, data_note)
    pdf.savefig(fig)
    plt.close(fig)


def build_monthly_picker_page(
    pdf: PdfPages,
    rows: list[dict[str, str]],
    start: date,
    end: date,
    data_note: str,
) -> None:
    fig = plt.figure(figsize=(11.69, 8.27))
    apply_theme(fig)
    add_header(fig, "Monthly Picker Metrics", f"Detail export included with weekly report | {start:%d %b %Y} - {end:%d %b %Y}")
    ax = fig.add_axes([0.03, 0.10, 0.94, 0.76])
    plot_monthly_picker_table(ax, rows)
    if len(rows) > 18:
        fig.text(0.05, 0.07, f"Showing first 18 of {len(rows)} monthly picker rows.", fontsize=8, color="#829AB1")
    add_footer(fig, data_note)
    pdf.savefig(fig)
    plt.close(fig)


def generate_report(
    weekly_records: list[MetricRecord],
    monthly_picker_rows: list[dict[str, str]],
    start: date,
    end: date,
    output_path: Path,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    data_note = (
        "Data source: CSV exports supplied to the generator."
        if weekly_records or monthly_picker_rows
        else "Data source unavailable in this run; all N/A sections require weekly and monthly CSV exports."
    )

    with PdfPages(output_path) as pdf:
        build_merchant_preview(pdf, weekly_records, start, end, data_note)
        venues = known_venues(weekly_records)
        if venues:
            for venue in venues:
                build_venue_page(pdf, venue, weekly_records, start, end, data_note)
        else:
            build_no_venue_page(pdf, start, end, data_note)

        build_metric_section(
            pdf,
            "Purchases",
            "Merchant and venue purchasing performance",
            weekly_records,
            PURCHASE_METRICS,
            ["Orders per venue", "Orders per Hour"],
            start,
            end,
            data_note,
        )
        build_metric_section(
            pdf,
            "Wolt+",
            "Wolt+ order and acquisition performance",
            weekly_records,
            WOLT_PLUS_METRICS,
            ["W+ Orders", "W+ New Users"],
            start,
            end,
            data_note,
        )
        build_metric_section(
            pdf,
            "Operations",
            "Fulfilment, timing, and prep performance",
            weekly_records,
            OPERATIONS_METRICS,
            ["Punctuality per Venue", "Prep Time per Venue"],
            start,
            end,
            data_note,
        )
        build_metric_section(
            pdf,
            "Quality",
            "Quality, offline, and lost-sales performance",
            weekly_records,
            QUALITY_METRICS,
            ["Rejections % per Venue", "Lost sales GOV EUR"],
            start,
            end,
            data_note,
        )
        build_metric_section(
            pdf,
            "Additions & Deductions",
            "Reason and fee breakdowns",
            weekly_records,
            ADDITION_DEDUCTION_METRICS,
            ["Rejection Reason", "Deduction Breakdown"],
            start,
            end,
            data_note,
        )
        build_metric_section(
            pdf,
            "Picker",
            "Picker usage per store",
            weekly_records,
            PICKER_METRICS,
            ["Picker Usage per Store"],
            start,
            end,
            data_note,
        )
        build_monthly_picker_page(pdf, monthly_picker_rows, start, end, data_note)


def main() -> None:
    args = parse_args()
    default_start, default_end = previous_full_week()
    start = parse_date(args.period_start, default_start)
    end = parse_date(args.period_end, default_end)
    output_path = args.output or output_path_for(start, end, "pdf")

    weekly_records = load_weekly_metrics(args.weekly_metrics)
    monthly_picker_rows = load_monthly_picker(args.monthly_picker)
    generate_report(weekly_records, monthly_picker_rows, start, end, output_path)
    print(output_path)


if __name__ == "__main__":
    main()
